server:
  port: 4000
  servlet:
    context-path: /config-server
spring:
  application:
    name: hiberus-config-server
  cloud:
    config:
      allow-override: true
      override-none: true
      override-system-properties: false
      server:
        git:
          uri: https://github.com/FcondeDev/hiberus-config-server.git
          search-paths: '{application}'